/* Généré par le tableau de bord de suivi — ne pas modifier à la main. */
window.SPRINTS = {
 "updated": "2026-10-05",
 "current": {
  "name": "S41",
  "start": "2026-10-05",
  "end": "2026-10-09",
  "goal": "",
  "status": "en_cours",
  "capacity": {
   "Pissano": 5.0,
   "David": 5.0
  },
  "load": {
   "Pissano": 0,
   "Non attribué": 0
  },
  "review": null,
  "tasks": [
   {
    "title": "Assainir les intitulés produits en production",
    "epic": "Intégration du stock MG – SI",
    "chantier": "Odoo",
    "person": "Pissano",
    "estimate": null,
    "status": "en_cours",
    "priority": 1,
    "carried_from": null,
    "from_incident": false
   },
   {
    "title": "Onboarding / offboarding : finaliser et mettre en production",
    "epic": "Compléments RH",
    "chantier": "Odoo",
    "person": "Pissano",
    "estimate": null,
    "status": "en_cours",
    "priority": 1,
    "carried_from": null,
    "from_incident": false
   },
   {
    "title": "Filtres dynamiques de la liste des étudiants (encore codés en dur)",
    "epic": "Mydocs — évolutions",
    "chantier": "Mydocs",
    "person": "Pissano",
    "estimate": null,
    "status": "en_cours",
    "priority": 1,
    "carried_from": null,
    "from_incident": false
   },
   {
    "title": "Développement du module Sprint Orchestra",
    "epic": "Module Sprint Orchestra",
    "chantier": "Odoo",
    "person": null,
    "estimate": null,
    "status": "en_cours",
    "priority": 2,
    "carried_from": null,
    "from_incident": false
   }
  ],
  "incidents": []
 },
 "next": null,
 "epics": [
  {
   "name": "Campus (vie associative…)",
   "chantier": "Zeno",
   "deadline": "",
   "owner": "Giovanni",
   "contact": "Laure",
   "description": "Input du BO.",
   "status": "actif",
   "tasks_total": 0,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 0,
   "in_sprint": false
  },
  {
   "name": "Compléments RAF",
   "chantier": "Odoo",
   "deadline": "",
   "owner": "David",
   "contact": "Constant",
   "description": "Évolutions continues côté RAF (Gescoth, paie, budget, compta).",
   "status": "actif",
   "tasks_total": 9,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 9,
   "in_sprint": false
  },
  {
   "name": "Compléments RH",
   "chantier": "Odoo",
   "deadline": "",
   "owner": "Pissano",
   "contact": "Christelle",
   "description": "Évolutions continues des modules RH.",
   "status": "actif",
   "tasks_total": 2,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 2,
   "in_sprint": true
  },
  {
   "name": "Intégration du stock MG – SI",
   "chantier": "Odoo",
   "deadline": "",
   "owner": "Pissano",
   "contact": "Jaurès, Amos",
   "description": "Stock, demandes & services, inventaire du pack SI.",
   "status": "actif",
   "tasks_total": 6,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 6,
   "in_sprint": true
  },
  {
   "name": "Module Sprint Orchestra",
   "chantier": "Odoo",
   "deadline": "",
   "owner": "",
   "contact": "",
   "description": "",
   "status": "actif",
   "tasks_total": 1,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 1,
   "in_sprint": true
  },
  {
   "name": "Mydocs — évolutions",
   "chantier": "Mydocs",
   "deadline": "",
   "owner": "Pissano",
   "contact": "",
   "description": "Pointage, QR codes, programmes, classes.",
   "status": "actif",
   "tasks_total": 1,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 1,
   "in_sprint": true
  },
  {
   "name": "Portail parent",
   "chantier": "Zeno",
   "deadline": "",
   "owner": "Modeste",
   "contact": "Ghislain & Franck",
   "description": "Refonte avec les données my.epitech.",
   "status": "actif",
   "tasks_total": 3,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 3,
   "in_sprint": false
  },
  {
   "name": "Pédagogie : anglais",
   "chantier": "Zeno",
   "deadline": "",
   "owner": "Alex",
   "contact": "Franck",
   "description": "",
   "status": "actif",
   "tasks_total": 0,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 0,
   "in_sprint": false
  },
  {
   "name": "Pédagogie étudiant & APE",
   "chantier": "Zeno",
   "deadline": "",
   "owner": "Edwin",
   "contact": "Ghislain & Franck",
   "description": "En finalisation.",
   "status": "actif",
   "tasks_total": 0,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 0,
   "in_sprint": false
  },
  {
   "name": "Career Center",
   "chantier": "Zeno",
   "deadline": "",
   "owner": "Spynel",
   "contact": "Idelphonse",
   "description": "Vigilance : le cahier des charges change énormément, à valider.",
   "status": "bloque",
   "tasks_total": 0,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 0,
   "in_sprint": false
  },
  {
   "name": "Modules juridiques",
   "chantier": "Odoo",
   "deadline": "",
   "owner": "David",
   "contact": "Faustin",
   "description": "Bloqué : disponibilité de Faustin, pas de besoins exprimés.",
   "status": "bloque",
   "tasks_total": 0,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 0,
   "in_sprint": false
  },
  {
   "name": "Admission",
   "chantier": "Zeno",
   "deadline": "",
   "owner": "Franck",
   "contact": "Fabrice et Charbel",
   "description": "Blocker : communication (WhatsApp).",
   "status": "a_venir",
   "tasks_total": 0,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 0,
   "in_sprint": false
  },
  {
   "name": "CRM AEIG (toutes marques)",
   "chantier": "Zeno",
   "deadline": "",
   "owner": "Franck",
   "contact": "Stéphanie & Gwen",
   "description": "Blocker : spécifications / CDC.",
   "status": "a_venir",
   "tasks_total": 0,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 0,
   "in_sprint": false
  },
  {
   "name": "Campagnes des marques : Digital Valley, Takabytes, AfrikEdutech, Future Studio",
   "chantier": "Zeno",
   "deadline": "",
   "owner": "Franck",
   "contact": "",
   "description": "Funnel à produire comme pour Croissance.",
   "status": "a_venir",
   "tasks_total": 0,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 0,
   "in_sprint": false
  },
  {
   "name": "Gestion du courrier",
   "chantier": "Odoo",
   "deadline": "",
   "owner": "",
   "contact": "",
   "description": "Courrier entrant / sortant dans Odoo. Cadrage fait le 24/09.",
   "status": "a_venir",
   "tasks_total": 1,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 1,
   "in_sprint": false
  },
  {
   "name": "Intégration Mydocs",
   "chantier": "Mydocs",
   "deadline": "",
   "owner": "",
   "contact": "",
   "description": "",
   "status": "a_venir",
   "tasks_total": 0,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 0,
   "in_sprint": false
  },
  {
   "name": "Automatisations (consolidation des retours, développement)",
   "chantier": "Odoo",
   "deadline": "",
   "owner": "David & Pissano",
   "contact": "Managers de tribus",
   "description": "",
   "status": "en_attente",
   "tasks_total": 0,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 0,
   "in_sprint": false
  },
  {
   "name": "Dashboards de pilotage et recette go-live V2",
   "chantier": "Odoo",
   "deadline": "",
   "owner": "David & Pissano",
   "contact": "Johanne",
   "description": "Calés sur la fin de Zeno P1.",
   "status": "en_attente",
   "tasks_total": 0,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 0,
   "in_sprint": false
  },
  {
   "name": "Procédures internes dans Odoo",
   "chantier": "Odoo",
   "deadline": "",
   "owner": "Pissano",
   "contact": "",
   "description": "Rédaction et diffusion des procédures ; procédures SI à implémenter.",
   "status": "en_attente",
   "tasks_total": 0,
   "tasks_done": 0,
   "days_total": 0,
   "days_done": 0,
   "unestimated": 0,
   "in_sprint": false
  }
 ],
 "backlog": [
  {
   "title": "Bon de commande : choisir le stock de livraison à la création (retour Rachad)",
   "epic": "Intégration du stock MG – SI",
   "chantier": "Odoo",
   "person": "Pissano",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Tester le coût moyen au niveau du produit (retour Rachad)",
   "epic": "Intégration du stock MG – SI",
   "chantier": "Odoo",
   "person": "Pissano",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Tableau de bord du pack SI (retour Amos)",
   "epic": "Intégration du stock MG – SI",
   "chantier": "Odoo",
   "person": "Pissano",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Notifier l'état d'un produit en stock (retour Amos)",
   "epic": "Intégration du stock MG – SI",
   "chantier": "Odoo",
   "person": "Pissano",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Motif obligatoire et validation hiérarchique pour maintenance et mise au rebut (retour Amos)",
   "epic": "Intégration du stock MG – SI",
   "chantier": "Odoo",
   "person": "Pissano",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Recrutement : grille d'évaluation générée par l'IA",
   "epic": "Compléments RH",
   "chantier": "Odoo",
   "person": "Pissano",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Bugs : navigation entre les années scolaires",
   "epic": "Compléments RAF",
   "chantier": "Odoo",
   "person": "David",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Bugs : paiements en avance, échéances, états de paiement",
   "epic": "Compléments RAF",
   "chantier": "Odoo",
   "person": "David",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Réaffectation des promos (données à réimporter)",
   "epic": "Compléments RAF",
   "chantier": "Odoo",
   "person": "David",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "10 KPI : frais de scolarité, boursiers, recouvrement, abandons, inscriptions…",
   "epic": "Compléments RAF",
   "chantier": "Odoo",
   "person": "David",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Paie : échelonnement des charges, état des salaires, avances, ordres de virement",
   "epic": "Compléments RAF",
   "chantier": "Odoo",
   "person": "David",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Paie : déclarations fiscales et sociales, imputation budgétaire",
   "epic": "Compléments RAF",
   "chantier": "Odoo",
   "person": "David",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Budget & compta : modèles d'écriture",
   "epic": "Compléments RAF",
   "chantier": "Odoo",
   "person": "David",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "États financiers SYSCOHADA révisé pour toutes les entités",
   "epic": "Compléments RAF",
   "chantier": "Odoo",
   "person": "David",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Ordres de virement MoMo MTN pour les fournisseurs",
   "epic": "Compléments RAF",
   "chantier": "Odoo",
   "person": "David",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Rédiger le cahier des charges",
   "epic": "Gestion du courrier",
   "chantier": "Odoo",
   "person": "Pissano",
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Intégrer les éléments V2",
   "epic": "Portail parent",
   "chantier": "Zeno",
   "person": null,
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Sélection de l'année et de l'emploi du temps",
   "epic": "Portail parent",
   "chantier": "Zeno",
   "person": null,
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  },
  {
   "title": "Rétablir l'accès puis mettre en ligne",
   "epic": "Portail parent",
   "chantier": "Zeno",
   "person": null,
   "estimate": null,
   "status": "a_faire",
   "priority": 2,
   "carried_from": null,
   "from_incident": false
  }
 ],
 "history": [],
 "done_epics": []
};
